### PR TITLE
UsefullBytes (ex ImageFrame)

### PR DESCRIPTION
**Pull request by xhenner**
It's somewhat ankward to have to reparse the result of the Bytes() method to have the real image file.
The informations about description and picture type are already in the String() method.
I just removed the useless part and let only the binary image in the result.

This way, I can simply do a ioutil.WriteFile("image.jpg", tag.Bytes(), 0644) to have my image

### CODE REVIEW

**Comment by mikkyang** [comment]
This functionality would be great, but could you possibly make a new method for it rather than using Bytes?

I intended the Bytes method to be used as an overloadable function that gets called when each frame of a tag is being written, so I tried to make all of the Bytes methods write correct ID3 tags.

**Comment by xhenner** [comment]
I just saw that too (I've start using the write function)
Working on a better patch right now

**Comment by xhenner** [comment]
I've added a UsefullBytes() method to all frames, which send only data bytes, and not metadata.
I changed the Framer interface accordingly.
I would suggest to change the Text() method to exclude the data, but it could break existing programs. And Text() output can be easily parsed.

**Comment by mikkyang** [comment]
Actually, shouldn't the Data() method be sufficient for what you're trying to do?

**Comment by xhenner** [comment]
I found that useful with these tags (among those I use for my app)
USLT (lyrics) : the text() method include the language, which I had to parse : I just need the lyrics themselves.
UFID : the text() method is useful to read the Owner identifier, but the content itself is not readable. It's used by picard, the musicbrainz tagger.

That's one usage for ImageFrame, IdFrame, UnsynchTextFrame. DataFrame had already a Data() method.
And, when using the lib, it's a lot easier to have a method which work without a type assessment.

**Comment by mikkyang** [comment]
I just checked the implementation of USLT, and the ParseUnsynchTextFrame method reads the language and other metadata before setting the text to the actual lyrics, so Text() should give you just the lyrics. If this isn't the case, could you show me an example where it parses incorrectly (file an issue, please)?

For UFID, I'm not aware of there being a Text() method. Could you clarify? The use that you contained in this pull request could be achieved using the Identifier() method.

In general I don't think there is a need for forcing _every_ frame to have a method that returns a binary representation of some portion of that frame's data. If you really wanted just the binary data, you could also just call Bytes() and take a slice that excludes the header (which should be a fixed number of bytes).

**Pull request closed without merging**
